version: "3"
services:
    db:
        ports:
            - 3306:3306
        container_name: dcim-db
        volumes:
            - mysql8:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=1mXpPYvMvuUGKk7
        image: mysql:8.0.36
        restart: always
    trimonsdcimapi:
        stdin_open: true
        tty: true
        ports:
            - 8080:8080
        container_name: dcim-bck
        environment:
            - spring_profiles_active=docker
            - JDBC_DATABASE_URL=jdbc:mysql://db:3306/trimons_dcim
            - JDBC_DATABASE_USERNAME=root
            - JDBC_DATABASE_PASSWORD=1mXpPYvMvuUGKk7
        build: ./api
        links:
            - db
        depends_on:
            - db
        restart: always
    trimonsdcimui:
        container_name: dcim-ui
        build: ./front
        links:
            - trimonsdcimapi
        depends_on:
            - trimonsdcimapi            
        ports:
            - 80:80
        restart: always           
volumes:
  mysql8:
    external: true
